### ISSUE TITLE
Slides 44-45: Interaction terms

### ISSUE THREAD

**Issue by nadezhdagesheva** [lse-me314/lse-me314.github.io#1]
Day 4 Slides: Linear Regression.
The right side of regression output is not visible. 

Please correct me if I am wrong.
The statement “The results in this estimation suggests that interactions are important.” is misleading. Even if the interaction term is significant, its estimated coefficient is 1.086e-03 = 0.001086, meanining that its effect is negligible on sales.

**Comment by kbenoit** [comment]
That's true! although it depends on the (still undefined) units of spending. This is is a good illustration of the difference between substantive and statistical significance.
