### ISSUE TITLE
Delineate content for week 9 and 10

### ISSUE THREAD

**Issue by jblumenau** [lse-me314/lse-me314.github.io#2]
@kbenoit -- you've put the title for week 10 as "Text classification and scaling". How much/what type of classification are you planning on doing? Currently I have circa 20 minutes on naive bayes in the week 9 lecture (updated slides should be in the relevant repo). Happy to drop this if you think it's going to duplicate what you are doing but either way we should make sure that we aren't repeating things.

**Comment by kbenoit** [comment]
For Day 9, I think it should just cover the fundamentals, such as tokenization, the idea of feature selection, some summary statistics, and dictionaries. IMHO it should not include NB.

Day 10 should cover Naive Bayes and other classifiers (e.g. SVM). I will also cover scaling models (wordscores, wordfish, CA, maybe affinity scaling).

That ok?

**Comment by jblumenau** [comment]
Yup, fine by me. I will just devote more time to complaining about how awful most dictionary methods are 👍
